steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/gkc-with-ci-cd', 'gkc-with-ci-cd=gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images:
- 'gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA'
