steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'gkc-with-ci-cd', '--region=us-central1', '--platform=managed', '--image=gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA']
