steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/for-poc-325210/gkc-with-ci-cd:$COMMIT_SHA']

