apiVersion: v1
kind: Service
metadata:
  name: gkc-with-ci-cd-service
spec:
  selector:
    app: gkc-with-ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
